apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchfront-deployment
  labels:
    app: benchfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchfront
  template:
    metadata:
      labels:
        app: benchfront
    spec:
      containers:
        - name: front
          image: benchcontainerregistry.azurecr.io/benchfront:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BackUrl
              valueFrom:
                configMapKeyRef:
                  name: benchapi-configmap
                  key: benchapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: benchfront-service
spec:
  type: LoadBalancer
  selector:
    app: benchfront
  ports:
    - protocol: TCP
      port: 80