apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchapi-deployment
  labels:
    app: benchapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchapi
  template:
    metadata:
      labels:
        app: benchapi
        service: benchapi
    spec:
      containers:
        - name: webapi
          image: crystal1337/benchapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: benchapi-service
  labels:
    app: benchapi
    service: benchapi
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: benchapi